version: 2

jobs:
  test:
    docker:
      - image: circleci/android:api-28-node8-alpha
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-repo-v2-{{ .Branch }}-{{ checksum "lightstep-tracer-android/build.gradle" }}
            - gradle-repo-v2-{{ .Branch }}-
            - gradle-repo-v2-
      - run:
          name: "set environment vars"
          command: |
            echo 'export TERM=dumb' >> $BASH_ENV
            source $BASH_ENV

      - run: yes | sdkmanager --licenses || exit 0
      - run: yes | sdkmanager --update || exit 0

      - run:
          name: "gradle dependencies"
          command: |
            # This is here twice because the first build fails to find
            # android-18 in /opt/android/sdk even though it exists.
            set +e
            ./gradlew dependencies || ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
            - /opt/android/sdk/
          key: gradle-repo-v2-{{ .Branch }}-{{ checksum "lightstep-tracer-android/build.gradle" }}
      - run: ./gradlew test

  # TODO: Try to recycle some of the logic, instead of having it all again for `release`.
  release:
    docker:
      - image: circleci/android:api-28-node8-alpha
    steps:
      - checkout
      - run: ls -la $HOME
      - restore_cache:
          keys:
            - gradle-repo-v2-{{ .Branch }}-{{ checksum "lightstep-tracer-android/build.gradle" }}
            - gradle-repo-v2-{{ .Branch }}-
            - gradle-repo-v2-
      - run:
          name: "set environment vars"
          command: |
            echo 'export TERM=dumb' >> $BASH_ENV
            source $BASH_ENV

      - run: yes | sdkmanager --licenses || exit 0
      - run: yes | sdkmanager --update || exit 0

      - run:
          name: "gradle dependencies"
          command: |
            # This is here twice because the first build fails to find
            # android-18 in /opt/android/sdk even though it exists.
            set +e
            ./gradlew dependencies || ./gradlew dependencies
      - run:
          name: Deploying
          command: |
            mkdir ~/.gpg-lightstep
            export GNUPGHOME=~/.gpg-lightstep
            echo -e "$GPG_SECRET_KEY" | gpg --import
            # HORRIBLE HACK. Thanks, Gradle: https://github.com/gradle/gradle/issues/888
            gpg --export-secret-keys >~/.gpg-lightstep/secring.gpg
            #echo "signing.keyId=$GPG_KEY_NAME" >> gradle.properties
            #echo "signing.secretKeyRingFile=~/.gpg-lightstep/secring.gpg" >> gradle.properties
            make publish
      - save_cache:
          paths:
            - ~/.gradle
            - /opt/android/sdk/
          key: gradle-repo-v2-{{ .Branch }}-{{ checksum "lightstep-tracer-android/build.gradle" }}

workflows:
  version: 2
  test:
    jobs:
      - test
  release:
    jobs:
      - release:
          context: release-context
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*$/
            branches:
              ignore: /.*/

