version: 2

jobs:
  test:
    docker:
      - image: circleci/android:api-28-node8-alpha
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-repo-v1-{{ .Branch }}-{{ checksum "lightstep-tracer-android/build.gradle" }}
            - gradle-repo-v1-{{ .Branch }}-
            - gradle-repo-v1-
      - run:
          name: "gradle dependencies"
          command: |
            export TERM=dumb

            # This is here twice because the first build fails to find
            # android-18 in /opt/android/sdk even though it exists.
            set +e
            ./gradlew dependencies || ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-repo-v1-{{ .Branch }}-{{ checksum "lightstep-tracer-android/build.gradle" }}
      - run: make test

workflows:
  version: 2
  test:
    jobs:
      - test

