version: 2

jobs:
  test:
    docker:
      - image: circleci/android:api-28-node8-alpha
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-repo-v1-{{ .Branch }}-{{ checksum "lightstep-tracer-javascript/build.gradle" }}
            - gradle-repo-v1-{{ .Branch }}-
            - gradle-repo-v1-
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-repo-v1-{{ .Branch }}-{{ checksum "lightstep-tracer-javascript/build.gradle" }}
      - run: make test

workflows:
  version: 2
  test:
    jobs:
      - test

